"""
Pydantic schemas for analysis requests and responses.
"""
from pydantic import BaseModel, Field
from typing import Optional


class AnalyzeRequest(BaseModel):
    """Schema for text analysis request."""
    text: str = Field(..., min_length=10, max_length=50000, description="Text to analyze")
    candidate_labels: Optional[list[str]] = Field(
        default=["technology", "politics", "sports", "entertainment", "business", "health", "science"],
        description="Categories for zero-shot classification"
    )


class AnalyzeResponse(BaseModel):
    """Schema for analysis response."""
    category: str = Field(..., description="Predicted category from Hugging Face")
    score: float = Field(..., description="Confidence score (0-1)")
    summary: str = Field(..., description="Summary generated by Gemini")
    tone: str = Field(..., description="Detected tone: positive, neutral, or negative")
    
    class Config:
        json_schema_extra = {
            "example": {
                "category": "technology",
                "score": 0.95,
                "summary": "This article discusses recent advances in AI technology...",
                "tone": "positive"
            }
        }
